FROM node:18-alpine

ENV USER=node \
    USER_ID=1000 \
    USER_GID=1000 \
    PASSWORD=pass

# create user
RUN apk add --no-cache shadow && \
    usermod -u ${USER_ID} ${USER} && \
    groupmod -g ${USER_GID} ${USER} && \
    apk add doas; \
    echo ${USER}:${PASSWORD} | chpasswd && \
    echo "permit nopass :${USER} as root" > /etc/doas.d/doas.conf && \
    apk del shadow

# switch to non-root user
USER ${USER}

# install global dependencies
RUN doas npm i -g npm && \
    doas apk update && \
    doas apk add git

# copy application files and install local dependencies
WORKDIR /workspace/app
COPY ./ ./
RUN doas npm i
