FROM golang:1.19-alpine as local

ENV USER=yyyoichi \
    USER_ID=1000 \
    USER_GID=1000 \
    PASSWORD=pass

# now creating user
RUN apk add --no-cache shadow && \
    addgroup -g ${USER_GID} -S ${USER} && \
    adduser  -u ${USER_ID} -G ${USER}  -s /bin/sh -D ${USER} &&  \
    apk add doas; \
    echo ${USER}:${PASSWORD} | chpasswd; \
    echo "permit nopass :${USER} as root" > /etc/doas.d/doas.conf  && \
    apk del shadow

USER ${USER}

WORKDIR /workspace/api/
COPY ./ ./

RUN doas apk update && \
    doas apk add build-base && \
    doas apk add git

RUN doas go mod tidy && \
    /usr/local/go/bin/go install -v github.com/cweill/gotests/gotests@v1.6.0 && \
    /usr/local/go/bin/go install -v github.com/fatih/gomodifytags@v1.16.0 && \
    /usr/local/go/bin/go install -v github.com/josharian/impl@v1.1.0 && \
    /usr/local/go/bin/go install -v github.com/haya14busa/goplay/cmd/goplay@v1.0.0 && \
    /usr/local/go/bin/go install -v github.com/go-delve/delve/cmd/dlv@latest && \
    /usr/local/go/bin/go install -v honnef.co/go/tools/cmd/staticcheck@latest && \
    /usr/local/go/bin/go install -v golang.org/x/tools/gopls@latest
