FROM golang:1.19-alpine as base

WORKDIR /workspace/api/

# COPY go.mod go.sum ./
# RUN go mod download
COPY ./ ./

RUN go mod tidy

# CMD ["./main"]

FROM base as local

# RUN go install -v github.com/cweill/gotests/gotests \
#   github.com/fatih/gomodifytags \
#   github.com/josharian/impl \
#   github.com/haya14busa/goplay/cmd/goplay \
#   github.com/go-delve/delve/cmd/dlv \
#   honnef.co/go/tools/cmd/staticcheck \
#   golang.org/x/tools/gopls \
#   github.com/ramya-rao-a/go-outline 
RUN apk add git