FROM golang:1.19-alpine as local

ENV USER=yyyoichi USER_ID=1000 USER_GID=1000

# now creating user
RUN apk add doas; \
    addgroup -g ${USER_GID} -S ${USER} && \
    adduser  -u ${USER_ID} -G ${USER}  -s /bin/sh -D ${USER} &&  \
    echo ${USER} | chpasswd; \
    echo "permit ${USER} as root" > /etc/doas.d/doas.conf

WORKDIR /workspace/api/

USER root

COPY ./ ./
RUN go mod tidy
RUN apk add build-base
RUN apk add git

RUN chown -R ${USER_ID}:${USER_GID} /workspace/api/
USER ${USER}

